### ISSUE TITLE
igmguesses voigt profile fitting

### ISSUE THREAD

**Issue by ntejos** [xastropy/xastropy#74]
Make sure that the model works (relevant line in igmguesses.py 474):

`self.model = lav.voigt_from_abslines(self.spec.dispersion,gdlin, fwhm=self.fwhm)#,debug=True)`

Basically the voigt profile is being done by linetools now `lav` and require the AbsLines in `gdlin` to have the column density attribute with units, whereas IGMGuesses.py was originally implemented without. This may require further changes in other parts of the code relevant to updating the components, and checking values for `logN` vs `N` (igmguesses worked in `logN` mostly).

**Comment by profxj** [comment]
Can you tell me how to test it?
Am rusty on this GUI.

**Comment by ntejos** [comment]
You can test it by trying to define a component in an absorption line (`A`
in both sides of the line); that should give you the error.
