### ISSUE TITLE
IGMGuesses broken

### ISSUE THREAD

**Issue by ntejos** [xastropy/xastropy#78]
IGMGuesses broken because some modules have been removed in the last PR, including: 

- xastropy.xguis.utils

**Comment by profxj** [comment]
Addressed by PR #79.

**Comment by ntejos** [comment]
IGMGuesses broken again after refactoring of guis modules.

**Comment by profxj** [comment]
on it.

X

----------------------------------------------
J. Xavier Prochaska
UCO/Lick Observatory
1156 High St.
UC Santa Cruz
Santa Cruz, CA 95064

http://www.ucolick.org/~xavier/
http://imps.ucolick.org/
http://www.qpqsurvey.org/
http://k1dm3.ucolick.org/
http://www.ucolick.org/~xavier/IDL/index.html
https://github.com/profxj/xastropy

831-459-2135 (Direct)
831-459-2991 (UCO/Lick Main)
831-459-5244 (Fax)

**Comment by ntejos** [comment]
The guis are working ok, and I believe that update_model() is ok too. Now the issue is that the model is not being fitted properly, so I think the problem is in fit_component() somewhere...

**Comment by ntejos** [comment]
Seems ok apart for plotting residuals which I will try to fix later. Will close for now. Thanks!
