### ISSUE TITLE
IGMGuesses enhancements

### ISSUE THREAD

**Issue by ntejos** [xastropy/xastropy#87]
- Add criteria for displaying ion species based on a equivalent width limit
- ~~Solve bug for ion species with '*' in their names~~
- ~~Add doctring for all available commands~~
- Add keystroke for uploading a custom set of linelist (similar to current 'H' and 'U'). Consider widget instead.
- ~~Repair 'guessing line' capability.~~
- ~~Repair residual display~~

**Comment by profxj** [comment]
Happy to work on these with you.

**Comment by ntejos** [comment]
Great! 

Could you have a look at the bug for ion species with '*' in their names? You should be able to reproduce the bug by trying to fit a component in ion species with names containing '*'. Basically the code won't crash but it would be unable to fit the line.

**Comment by profxj** [comment]
I will if come by at 12:30pm. :)

X

----------------------------------------------
J. Xavier Prochaska
UCO/Lick Observatory
1156 High St.
UC Santa Cruz
Santa Cruz, CA 95064

http://www.ucolick.org/~xavier/
http://imps.ucolick.org/
http://www.qpqsurvey.org/
http://k1dm3.ucolick.org/
http://www.ucolick.org/~xavier/IDL/index.html
https://github.com/profxj/xastropy

831-459-2135 (Direct)
831-459-2991 (UCO/Lick Main)
831-459-5244 (Fax)

**Comment by ntejos** [comment]
Hi @profxj, can you create a pull request with the `'*'` issue solution? Thanks.

**Comment by profxj** [comment]
#89

X

> On Jan 28, 2016, at 9:27 AM, Nicolas Tejos <notifications@github.com> wrote:
> 
> Hi @profxj <https://github.com/profxj>, can you create a pull request with the '*' issue solution? Thanks.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/xastropy/xastropy/issues/87#issuecomment-176292399>.
> 
> !DSPAM:826,56aa4f90280141934222893!

----------------------------------------------
J. Xavier Prochaska
UCO/Lick Observatory
1156 High St.
UC Santa Cruz
Santa Cruz, CA 95064

http://www.ucolick.org/~xavier/
http://imps.ucolick.org/
http://www.qpqsurvey.org/
http://k1dm3.ucolick.org/
http://www.ucolick.org/~xavier/IDL/index.html
https://github.com/pyigm/pyigm
https://github.com/linetools/linetools

831-459-2135 (Direct)
831-459-2991 (UCO/Lick Main)
831-459-5244 (Fax)

**Comment by ntejos** [comment]
Thanks!

**Comment by ntejos** [comment]
Closing because most where addressed, and besides IGMGuesses has migrated to pyigm.
